routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\yearController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\AttendantController;
use App\Http\Controllers\ScoreListController;
use App\Http\Controllers\attentListController;
use App\Http\Controllers\StudentListController;
use App\Http\Controllers\RegisterStudentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::resource('admin/class',ClassController::class);
Route::resource('admin/year',yearController::class);
Route::resource('admin/student',StudentController::class);
Route::resource('admin/attendant',AttendantController::class);
Route::resource('admin/score',ScoreController::class);
Route::resource('admin/register',RegisterStudentController::class);
Route::resource('admin/home',HomeController::class);

Route::get('admin/class/{id}',[ClassController::class,'destroy']);
Route::get('admin/delete/{id}',[yearController::class,'destroy']);
Route::get('admin/edit/{id}',[yearController::class,'edit']);

Route::resource('admin/list',StudentListController::class);

Route::resource('admin/score_list',ScoreListController::class);
Route::resource('admin/attend_list',attentListController::class);

Route::get('admin/add',function(){
    return view('admin.RegisterStudent.add');
});
Route::get('/findclass/{id}',[RegisterStudentController::class, 'findclass'])->name('getclass');

app/Models/year.php
<?php

namespace App\Models;

use App\Models\Classes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class year extends Model
{
    use HasFactory;
    protected $table="years";
    protected $fillable=[
        'year'
    ];

    public function classes(){
        return $this->hasMany(Classes::class);
    }
}

app/Http/Controllers/yearController.php
<?php

namespace App\Http\Controllers;

use App\Models\year;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class yearController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data= year::all();
        
        return view('admin.years.index',['years'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
       $data=[];
       $data['years']=year::get();
        return view('admin.years.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        year::create([
            'year'  =>$request->year
        ]);

        return redirect('/admin/year');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data=year::find($id);
        return view('admin.years.edit',['years'=>$data]);
      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {        
        $data=year::findOrFail($id);
        $data::update([
            'year'  =>$request->year
        ]);
        return redirect('admin/year');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
       $data=year::find($id);
       $data->delete();
       return redirect()->route('year.index');
    }
    public function clickedit($id){
        $year=DB::select('select * from years where id=?',[$id]);
        return redirect()->route('year.index');
    }
}

resources/views/admin/years/create.blade.php
@extends('admin.layouts')
@section('content')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Year </title>
    @include('admin.includes.link')
    <link rel="stylesheet" href="{{ asset('css/create_year.css')}}">
</head>
<body>
  @if(Session::get('success'))
    <div class="alert alert-success">
      {{Session::get('success')}}
    </div>
  @endif
  @if(Session::get('fail'))
    <div class="alert alert-danger">
      {{Session::get('fail')}}
    </div>
  @endif
    <form action="{{route('year.store')}}" class="form" method="POST" >
    @csrf
    <div class="form-group" style="font-family: Khmer OS">
      <label for="email">ឆ្នាំសិក្សា</label>
      <input type="text" class="form-control" id="year" placeholder="2020-2021" name="year">
    </div>
    <div class="form-group">
    
   <input type="submit" Value="OK">
    </form>
</body>
</html>
@endsection

resources/views/admin/years/edit.blade.php
@extends('admin.layouts')

@section('content')
<form action="{{route('year.update',$years['id'])}}" class="form" method="POST" >
    @csrf
    <div class="form-group" style="font-family: Khmer OS">
      <label for="email">ឆ្នាំសិក្សា</label>
      <input type="hidden" class="form-control" id="id" value="{{$years['id']}}" placeholder="2020-2021" name="year">
      <input type="text" class="form-control" id="year" value="{{$years['year']}}" placeholder="2020-2021" name="year">
    </div>
    <div class="form-group">
    
   <input type="submit" Value="update">
    </form>
@endsection

resources/views/admin/years/index.blade.php
@extends('admin.layouts')
@include('admin.includes.link')
@section('content')


  
<button class="btn btn-danger"><a href="{{url('/admin/year/create')}}" style="color:black;font-family:Khmer OS">បង្កើតឆ្នាំសិក្សា</button>

<div class="year" style="padding:20px;box-shadow: box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

<table class="table" style="font-size:24px;border:2px solid black;">
    <tr style="background:	#696969; color:white">
        <th>កូដ</th>
        <th>ឆ្នាំសិក្សា</th>
        <th>ថ្ងៃទីបង្កើត</th>
        <th>បញ្ជា</th>
    </tr>
    
    @foreach($years as $year)
    <tr>
        <td>{{$year['id']}}</td>
        <td>{{$year['year']}}</td>
        <td>{{$year['created_at']}}</td>
        <td>
        <a href = 'edit/{{ $year->id }}'><i class="far fa-edit"></i></a>
        <a href = 'delete/{{ $year->id }}'><i class="fas fa-minus-circle"></i></a>   
      
        </td>
    </tr>
    @endforeach
  
</table>
    
</div>

@endsection

@push('js')
      

@endpush

resources/views/admin/years/login.blade.php
<?php
    $host="localhost:3306";
    $user="root";
    $pwd="";
    $db="school";

    $con=mysqli_connect($host,$user,$pwd,$db);
    if(!$con){
        echo"connection fail";

    }else{
            


        header("refresh:1; url=menu/menu.html");
    }
?>